
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  namespace: dev
spec:
  containers:
  - name: app-container
    image: nginx:latest
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: app-config # 引用 ConfigMap 名称
          key: username # 引用的键
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: password
  #   volumeMounts:
  #   - name: config-volume
  #     mountPath: /etc/config
  # volumes:
  # - name: config-volume
  #   configMap:
  #     name: app-config